name: Mirror Backup

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  backup:
    if: github.repository_owner == '1History'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Sourcecraft
        if: always()
        run: |
          # https://sourcecraft.dev/jiacai2050/eww-history-ext
          git push --tags --force \
          https://git:${{ secrets.SOURCECRAFT_TOKEN }}@git.sourcecraft.dev/jiacai2050/eww-history-ext.git \
          "refs/remotes/origin/*:refs/heads/*"
